### ISSUE TITLE
Right wheel is much harder to turn than the left wheel

### ISSUE THREAD

**Issue by bjmcternan** [Team293/Octabot_V2#2]
Currently, the right wheel is much harder to turn than the left. This may be affecting the autonomous driving routine and preventing the robot from turning and moving properly. 

This needs to be brought up with the mechanical team to get this fixed and looked at.

**Comment by bjmcternan** [comment]
We have brought up the issue with Dr. P. He will look into it.

**Comment by karthikappana35** [comment]
Octabot has been repaired and will be tested today

**Comment by karthikappana35** [comment]
Dr.p fixed this
